# Generated by Django 5.2.4 on 2025-11-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sentiment_label',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Sentiment classification label', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='sentiment_magnitude',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sentiment magnitude/strength from 0.0 to 1.0', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sentiment score from -1.0 (negative) to 1.0 (positive)', max_digits=4, null=True),
        ),
    ]
